welllahh/my_app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from . import views

app_name = "my_app"

urlpatterns = [
    path("", views.landing_page, name="home"),
    path("ai/food_nutrition/", views.inference_indofood_image, name="food_nutrition"),
    path("meal_plan/", views.meal_plan, name="meal_plan"),
    # path("admin/", admin.site.urls),
    path("register", views.register_user, name="register_known_user"),
    path(
        "register_anonymous",
        views.register_anonymous_user,
        name="register_anonymous_user",
    ),
    path("health_check/bmi", views.get_bmi_condition, name="get_bmi_condition"),
    path(
        "health_check/nutrition",
        views.get_health_condition_based_on_nutrition_val,
        name="get_health_condition_based_on_nutrition_val",
    ),
    path("health_progress/nutrition", views.catat_nutrisi, name="catat_nutrisi"),
    path("health_progress/bmi", views.catat_tinggi_berat, name="catat_tinggi_berat"),
    path("login", views.normal_login, name="normal_login"),
    path("anonymous_login", views.login_using_passphrase, name="anonymous_login"),
    path("ai/chatbot", views.get_chatbot_response, name="chatbot"),
    path("ai/chatbotpage", views.chatbot_page, name="chatbotpage"),
    path("ai/chatbotpage/<uuid:id>", views.chatbot_page, name="chatbotpage"),
    path("dashboard", views.dashboard, name="dashboard"),
    path("delete_nutrition/<uuid:pk>", views.delete_nutrition, name="delete_nutrition"),
    path("logout", views.logout_view, name="logout"),
    path("riwayat", views.riwayat_penyakit, name="riwayat"),
    path("add_nutrition", views.add_nutrition, name="add_nutrition"),
    path("add_riwayat", views.add_riwayat, name="add_riwayat"),
    path("delete_riwayat/<int:pk>", views.delete_riwayat, name="delete_riwayat"),
    path("add_target", views.add_target, name="add_target"),
    path("add_blood", views.add_blood_condition, name="add_blood"),
    path("feature_tour", views.feature_tour, name="feature_tour"),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

welllahh/welllahh/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path("admin/", admin.site.urls),
]

welllahh/my_app/models.py
from uuid import uuid4

from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone

# Create your models here.


class CustomUser(models.Model):
    customer_id = models.UUIDField(primary_key=True, default=uuid4, editable=False)
    status_choices = [("any", "anonymous"), ("knw", "known")]
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    age = models.IntegerField(blank=True, null=True)
    parent = models.ForeignKey("self", on_delete=models.CASCADE, blank=True, null=True)
    secret_phrase = models.CharField(max_length=100)
    status = models.CharField(max_length=len("anonymous"), choices=status_choices)

    def __str__(self):
        return f"{self.user.username}-{self.status}"


class UserBodyInfo(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid4, editable=False)
    weight = models.IntegerField()
    muscle_mass = models.IntegerField(blank=True, null=True)
    height = models.IntegerField()
    fat_mass = models.IntegerField(blank=True, null=True)
    check_time = models.DateField()
    custom_user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)

    def __str__(self) -> str:
        return self.custom_user.user.username


class ChatSession(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid4, editable=False)
    message_from = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    session_title = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)


class Message(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid4, editable=False)
    prompt_content = models.TextField()
    chatbot_content = models.TextField()
    context = models.TextField()
    chat_session = models.ForeignKey(ChatSession, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)


class Token(models.Model):
    token_id = models.UUIDField(primary_key=True, default=uuid4, editable=False)
    token = models.CharField(max_length=255)
    custom_user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)


class NutritionType(models.TextChoices):
    CALORY = "Calory", "Calory"
    BLOOD_SUGAR = "Blood Sugar", "Blood Sugar"
    PROTEIN = "Protein", "Protein"
    FAT = "Fat", "Fat"
    CARBS = "Carbs", "Carbs"
    CHOLESTEROL = "Cholesterol", "Cholesterol"
    URIC_ACID = "URIC_ACID", "URIC_ACID"
    BLOOD_PRESSURE = "BLOOD_PRESSURE", "BLOOD_PRESSURE"


class BloodCodition(models.Model):
    blood_sugar = models.DecimalField(max_digits=10, decimal_places=2)
    uric_acid = models.DecimalField(max_digits=10, decimal_places=2)
    cholesterol = models.DecimalField(max_digits=10, decimal_places=2)
    blood_pressure = models.DecimalField(max_digits=10, decimal_places=2)
    check_time = models.DateTimeField(default=timezone.now)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)


class FeatureTour(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid4, editable=False)
    dashboard_page = models.BooleanField(default=False)
    food_nutrition_page = models.BooleanField(default=False)
    medical_history_page = models.BooleanField(default=False)
    add_nutrition_page = models.BooleanField(default=False)
    add_medical_history_page = models.BooleanField(default=False)
    meal_plan_page = models.BooleanField(default=False)
    record_bmi_page = models.BooleanField(default=False)
    add_target_page = models.BooleanField(default=False)
    add_blood_condition_page = models.BooleanField(default=False)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)


class NutritionProgress(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid4, editable=False)
    check_time = models.DateTimeField(default=timezone.now)
    nutrition_name = models.CharField(max_length=255, default=None)
    calorie = models.DecimalField(max_digits=10, decimal_places=2)
    carbs = models.DecimalField(max_digits=10, decimal_places=2)
    protein = models.DecimalField(max_digits=10, decimal_places=2)
    fat = models.DecimalField(max_digits=10, decimal_places=2)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.nutrition_name} - {self.calorie} at {self.check_time}"


class RiwayatPenyakit(models.Model):
    nama_penyakit = models.CharField(max_length=255)
    deskripsi_penyakit = models.CharField(max_length=255)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    check_time = models.DateTimeField(default=timezone.now)


class TargetPlan(models.Model):
    target_calorie = models.IntegerField()
    target_carbs = models.IntegerField()
    target_protein = models.IntegerField()
    target_fat = models.IntegerField()
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)

welllahh/my_app/views.py
import datetime
import json
import random
import string
from datetime import date
from uuid import uuid4

import numpy as np
import tensorflow as tf
from constraint import *
from django.conf import settings
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.files.storage import default_storage
from django.db.models import Q, Sum, Avg

# from .medical_ai_chatbot import answer_pipeline
from django.db.models.functions import TruncDate
from django.http.response import HttpResponse, JsonResponse
from django.shortcuts import redirect, render
from django.utils import timezone
from django.views.decorators.csrf import csrf_exempt
from keras.applications.imagenet_utils import decode_predictions
from keras.preprocessing.image import img_to_array, load_img
from PIL import Image
from sklearn.metrics.pairwise import cosine_similarity
from tensorflow.python.keras.backend import set_session

from .medical_ai_chatbot import answer_pipeline
from .models import *


def landing_page(request):
    return render(request, "welllahh_landing_page.html")


@csrf_exempt
def register_user(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
        email = request.POST.get("email")
        age = request.POST.get("age")

        user_exists = CustomUser.objects.filter(
            Q(user__username=username) | Q(user__email=email)
        ).exists()
        if user_exists:
            return JsonResponse(
                {"message": "Username tersebut sudah ada, ganti username lain yaa."}
            )
        user = User.objects.create_user(
            username=username, password=password, email=email
        )
        custom_user = CustomUser(
            user=user,
            secret_phrase=generate_random_string,
            status="known",
            age=age,
        )
        custom_user.save()
        login(request, user)
        return redirect("my_app:catat_tinggi_berat")
    return render(request, "register.html")


@csrf_exempt
def register_anonymous_user(request):
    if request.method == "POST":
        username = request.POST.get("username")
        user = User.objects.create(username=username)
        custom_user = CustomUser(
            user=user, passphrase=generate_random_string, status="anonymous"
        )
        custom_user.save()
        return redirect("my_app:dashboard")
    return render(request, "anonymous_register.html")


@csrf_exempt
def normal_login(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user=user)
            return redirect("my_app:dashboard")
        else:
            return JsonResponse(
                {"message": f"invalid creds {user}-{username}-{password}"}
            )
    return render(request, "login.html")


@csrf_exempt
def login_using_passphrase(request):
    if request.method == "POST":
        secret_phrase = request.POST.get("secret_phrase")
        user = User.objects.filter(secret_phrase=secret_phrase).get()
        user = authenticate(username=user.username, password=user.password)
        if user is not None:
            login(request, user=user)
            return redirect("my_app:dashboard")
        else:
            return JsonResponse({"message": "invalid phrase"})
    return render(request, "anonymous_login.html")


def generate_login_token(request):
    pass


def GetFoodNutrition(foodName: str):
    foodName = foodName.lower()
    myFoodNutrition = {}
    for idx, food in settings.INDOFOOD_NUTRITIONS_DF.iterrows():
        if foodName == food["food_name"]:
            myFoodNutrition["calories"] = food["calories"].split("kcal")[0]
            myFoodNutrition["fat"] = food["fat"]
            myFoodNutrition["carbohydrate"] = food["carbohydrate"]
            myFoodNutrition["proteins"] = food["proteins"]
    return myFoodNutrition


def inference_indofood_image(request):
    if request.method == "POST":
        if request.POST.get("submit-tracker"):
            nutrition_name = request.POST.get("nutrition-name")
            calorie = request.POST.get("calorie").replace("kcal", "")
            carbs = request.POST.get("carbs").replace("g", "")
            protein = request.POST.get("protein").replace("g", "")
            fat = request.POST.get("fat").replace("g", "")
            user = CustomUser.objects.get(user=request.user)
            nutrition = NutritionProgress(
                user=user,
                nutrition_name=nutrition_name,
                calorie=calorie,
                carbs=carbs,
                protein=protein,
                fat=fat,
            )
            nutrition.save()
            return redirect("my_app:dashboard")
        file = request.FILES.get("imageFile")
        if file is not None:
            file_name = default_storage.save(file.name, file)
            file_url = default_storage.path(file_name)

            image = load_img(file_url, target_size=(320, 320))
            numpy_array = img_to_array(image)

            image_batch = np.expand_dims(numpy_array, axis=0)
            prediction = settings.INDOFOOD_IMAGE_MODEL.predict(image_batch)

            labels = settings.INDOFOOD_IMAGE_LABELS
            res = labels[tf.argmax(prediction[0])]

            nutritions = GetFoodNutrition(res[1])
            return render(
                request,
                "food_nutrition.html",
                {"predictions": res, "nutritions": nutritions},
            )
        else:
            return
    else:
        feature_tour = get_feature_tour(request)
        feature_tour_item = feature_tour["food_nutrition_page"]

        return render(
            request,
            "food_nutrition.html",
            {
                "name": "Unknown",
                "nutritions": {
                    "calories": 0,
                    "fat": 0,
                    "carbohydrate": 0,
                    "proteins": 0,
                },
                "feature_tour": feature_tour_item,
            },
        )


def generate_random_string(length=12):
    characters = string.ascii_letters + string.digits
    return "".join(random.choice(characters) for _ in range(length))


def get_bmi_condition(request):
    if request.method == "GET":
        weight = request.POST.get("weight")
        height = request.POST.get("height")
        bmi = round((weight / (height * height)), 2)
        # https://en.wikipedia.org/wiki/Body_mass_index
        if bmi >= 30.0:
            return JsonResponse(data={"condition": "Obesitas"})
        elif bmi >= 25.0 and bmi < 30:
            return JsonResponse(data={"condition": "Overweight (Pre-obesitas)"})
        elif bmi >= 18.5 and bmi < 25.0:
            return JsonResponse(data={"condition": "Normal"})
        elif bmi >= 17.0 and bmi < 18.5:
            return JsonResponse(data={"condition": "Underweight (Mild thinness)"})
        elif bmi >= 16.0 and bmi < 17.0:
            return JsonResponse(data={"condition": "Underweight (Moderate thinness)"})
        elif bmi >= 16.0 and bmi < 17.0:
            return JsonResponse(data={"condition": "Underweight (Severe thinness)	"})


def get_health_condition_based_on_nutrition_val(request):
    if request.method == "GET":
        nutrition_type = request.POST.get("nutrition_type")
        nutrition_value = request.POST.get("nutrition_value")
        user = request.user
        custom_user = CustomUser.objects.get(user=user)
        user_age = custom_user.age
        if nutrition_type == "BLOOD_SUGAR":
            # https://www.halodoc.com/kesehatan/diabetes?srsltid=AfmBOorAHmPVZ_SFLW0q8RSkk8xjPeMjfor1bEsOx3HHs1kgrNbvApR9

            if nutrition_value >= 126:
                return JsonResponse(data={"disease_prediction": "diabetes"})
            elif nutrition_value >= 100 and nutrition_value <= 125:
                return JsonResponse(data={"disease_prediction": "prediabetes"})
            else:
                return JsonResponse(data={"disease_prediction": "normal"})

        if nutrition_type == "CHOLESTEROL":
            if user_age >= 20:
                if nutrition_value > 200:
                    # https://www.siloamhospitals.com/en/informasi-siloam/artikel/kadar-kolesterol-normal
                    return JsonResponse(
                        data={"disease_prediction": "Penyakit Jantung dan stroke"}
                    )
                else:
                    return JsonResponse(data={"disease_prediction": "normal"})
            else:
                if nutrition_value > 170:
                    # https://www.siloamhospitals.com/en/informasi-siloam/artikel/kadar-kolesterol-normal
                    return JsonResponse(
                        data={"disease_prediction": "Penyakit Jantung dan stroke"}
                    )
                else:
                    return JsonResponse(data={"disease_prediction": "normal"})
        if nutrition_type == "URIC_ACID":
            # asam urat
            # https://www.siloamhospitals.com/en/informasi-siloam/artikel/prosedur-cek-asam-urat
            if nutrition_value >= 7.0:
                return JsonResponse(
                    data={"disease_prediction": "Serangan Asam Urat Dan Batu Ginjal"}
                )

            else:
                return JsonResponse(data={"disease_prediction": "normal"})
        if nutrition_type == "BLOOD_PRESSURE":
            # https://www.siloamhospitals.com/informasi-siloam/artikel/mengenal-tekanan-darah-normal
            if user_age >= 18:
                if nutrition_value > 120:
                    return JsonResponse(data={"disease_prediction": "Hipertensi"})
                else:

welllahh/my_app/templates/add_blood.html
{% extends "base_dashboard_cantik.html" %} {%load static%} {% block content %}
<main>
  <header>
    <div>
      <h2>Record Your Blood Condition</h2>
      <p class="current-date">{% now "d-m-Y" %}</p>
    </div>
  </header>
  <form method="POST">
    {% csrf_token %}
    <div id="blood-condition-form" class="add-bmi-container">
      <div class="input-container">
        <div class="input-box">
          <label>Blood Sugar</label>
          <input
            type="number"
            name="blood_sugar"
            placeholder="{{blood_data.blood_sugar}}"
            value="{{blood_data.blood_sugar}}"
          />
        </div>
        <div class="input-box">
          <label>Uric Acid</label>
          <input
            type="number"
            name="uric_acid"
            placeholder="{{blood_data.uric_acid}}"
            value="{{blood_data.uric_acid}}"
          />
        </div>
        <div class="input-box">
          <label>Cholesterol</label>
          <input
            type="number"
            name="cholesterol"
            placeholder="{{blood_data.cholesterol}}"
            value="{{blood_data.cholesterol}}"
          />
        </div>
        <div class="input-box">
          <label>Blood Pressure</label>
          <input
            type="number"
            name="blood_pressure"
            placeholder="{{blood_data.blood_pressure}}"
            value="{{blood_data.blood_pressure}}"
          />
        </div>
        <button id="blood-condition-btn" type="submit" class="calculate-btn">
          Submit
        </button>
      </div>
    </div>
  </form>
</main>
{% endblock content %} {% block script%}

<script src="{% static 'js/add_bmi.js' %}"></script>

<!-- prettier-ignore -->
{{ feature_tour|json_script:"feature_tour" }}
<script>
  const feature_tour = JSON.parse(
    document.getElementById("feature_tour").textContent
  );

  let sidebarItems = document.querySelectorAll(".sidebar .item");
  for (let item of sidebarItems) {
    item.id = "";
  }
  sidebarItems[9].id = "active";

  const driver = window.driver.js.driver;

  const driverObj = driver({
    showProgress: true,
    steps: [
      {
        element: ".page-header",
        popover: {
          title: "Record Your Blood Condition",
          description:
            "Pada page ini, anda dapat mencatat kadar gula darah, uric acid, kolesterol, dan tekanan darah anda.",
        },
      },
      {
        element: "#blood-condition-form",
        popover: {
          title: "Record Your Blood Condition Form",
          description:
            "Isi form dengan data kadar gula darah, uric acid, kolesterol, dan tekanan darah anda.",
        },
      },

      {
        element: "#blood-condition-btn",
        popover: {
          title: "Blood Condition Button",
          description:
            "Jika sudah mengisi form, klik tombol ini untuk menyimpan data kadar gula darah, uric acid, kolesterol, dan tekanan darah anda.",
        },
      },
    ],
    smoothScroll: true,
  });

  if (feature_tour == false) {
    driverObj.drive();
  }

  // post feature tour
  function getCookie(name) {
    let cookieValue = null;
    if (document.cookie && document.cookie !== "") {
      const cookies = document.cookie.split(";");
      for (let i = 0; i < cookies.length; i++) {
        const cookie = cookies[i].trim();
        if (cookie.substring(0, name.length + 1) === name + "=") {
          cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
          break;
        }
      }
    }
    return cookieValue;
  }

  const csrftoken = getCookie("csrftoken");

  $(document).ready(function () {
    $.ajaxSetup({
      beforeSend: function (xhr, settings) {
        if (!/^GET|HEAD|OPTIONS|TRACE$/i.test(settings.type)) {
          xhr.setRequestHeader("X-CSRFToken", csrftoken);
        }
      },
    });

    $.ajax({
      url: "http://localhost:8000/my_app/feature_tour",
      type: "POST",
      contentType: "application/json",
      data: JSON.stringify({
        item: "add_blood_condition_page",
      }),
      success: function (response) {
        console.log("success");
      },
      error: function (xhr, status, error) {
        console.log("error POST request: ", error);
      },
    });
  });
</script>
{% endblock script%}

welllahh/my_app/templates/add_nutrition.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Welllah Add Food</title>
    {% load static %}
    <link href="{% static 'css/register.css' %}" rel="stylesheet">
    <link href="{% static 'css/styles.css' %}" rel="stylesheet">
 </head>
  <body>
   <section class="container">
      <header>
        Add Food
      </header>
     <form class="form" method="post">
        {% csrf_token %}
        <div class="input-box">
          <label>Food Name</label>
          <input type="text" name="nutrition_name" placeholder="ayam goyeng">
        </div>
        <div class="input-box">
          <label>Calorie</label>
          <input type="number" name="calorie" placeholder="1000">
        </div>
        <div class="input-box">
          <label>Protein</label>
          <input type="number" name="protein" placeholder="500">
        </div>
        <div class="input-box">
          <label>Carbs</label>
          <input type="number" name="carbs" placeholder="800">
        </div>
        <div class="input-box">
          <label>Fat</label>
          <input type="number" name="fat" placeholder="800">
        </div>
        <div style="display:flex;flex-direction:row;gap:15px;padding:10px;"><button type="submit">Submit</button><button type="submit" name="redirect" value="true">Submit and Go to Dashboard</button></div>
        
      </form>
    </section>
  </body>
</html>

welllahh/my_app/templates/base.html
{%load static%}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/remixicon@3.4.0/fonts/remixicon.css" rel="stylesheet" />

    <link href="{% static 'css/styles.css' %}" rel="stylesheet">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" />

    <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>

    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <title>Welllah | Health Care</title>
</head>

<body>
    <div>
        <nav class="section__container nav__container">
            <div class="nav__logo">
                <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
                <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
                Welllah <span>care</span>
            </div>
            <ul class="nav__links">
                <li class="link"> <a href="{% url 'my_app:home' %}">Home</a></li>
                <li class="link"> <a href="{% url 'my_app:dashboard' %}">Dashboard</a></li>
                <li class="link"> <a href="{% url 'my_app:chatbotpage' %}">Chatbot</a></li>
            </ul>
            <div class="nav_buttons">
                <button class="btn">Login</button>
                <button class="btn">Register</button>
            </div>
        </nav>

        {% block content %} {% endblock content %}

        <footer class="footer">
            <div class="section__container footer__container">
                <div class="footer__col">
                    <h3>
                        Welllahh
                    </h3>
                </div>
                <div class="footer__col">
                    <h4>About Us</h4>
                    <p>Home</p>
                    <p>About Us</p>
                    <p>Terms & Conditions</p>
                </div>

                <div class="footer__col">
                    <h4>Services</h4>
                    <p>Search Terms</p>
                    <p>Privacy Policy</p>
                </div>




                <div class="footer__col">
                    <h4>Contact Us</h4>
                    <p>
                        <i class="ri-map-pin-2-fill"></i> Pogung, Sleman, Yogyakarta
                    </p>
                    <p>
                        <i class="ri-mail-fill"></i> welllahhh@gmail.com
                    </p>
                    <p>
                        <i class="ri-phone-fill"></i> 0822222222
                    </p>
                </div>
            </div>
            <div class="footer__bar">
                <div class="footer__bar__content">
                    <p>
                        &copy; 2024 Welllahh. All Rights Reserved
                    </p>
                    <div class="footer__socials">
                        <span><i class="ri-instagram-line"></i></span>
                        <span><i class="ri-facebook-fill"></i></span>
                        <span><i class="ri-heart-fill"></i></span>
                        <span><i class="ri-twitter-fill"></i></span>

                    </div>
                </div>
            </div>
        </footer>
    </div>

    {% block script %} {% endblock script %}
</body>

</html>

welllahh/my_app/templates/dashboard.html
{% extends "base_dashboard.html" %} {% block content %}

<section class="main">
  <div class="main-top">
    <h1>Summary</h1>
    <i class="fas fa-user-cog"></i>
  </div>
  <div class="users">
    <div class="card">
      <h2>Today Summary</h2>

      <div class="summary-calories">
        <h2 class="calorie">Calories</h2>
        <p class="calorie" id="total-today-calories">{{today_calory}}</p>
      </div>

      <div class="summary-details">
        <div class="detes">
          <h5 class="carbs">Carbs</h5>
          <p class="carbs" id="total-today-carbs">{{today_carbs}}</p>
        </div>
        <div class="detes">
          <h5 class="fat">Fat</h5>
          <p class="fat" id="total-today-fat">{{today_fat}}</p>
        </div>
        <div class="detes">
          <h5 class="protein">Protein</h5>
          <p class="protein" id="total-today-protein">{{today_protein}}</p>
        </div>
      </div>
    </div>

    <div class="card">
      <h2>Last 7 Day Summary</h2>

      <div class="summary-calories">
        <h2 class="calorie">Calories</h2>
        <p class="calorie" id="total-week-calories">{{weekly_calory}}</p>
      </div>

      <div class="summary-details">
        <div class="detes">
          <h5 class="carbs">Carbs</h5>
          <p class="carbs" id="total-week-carbs">{{weekly_carbs}}</p>
        </div>
        <div class="detes">
          <h5 class="fat">Fat</h5>
          <p class="fat" id="total-week-fat">{{weekly_fat}}</p>
        </div>
        <div class="detes">
          <h5 class="protein">Protein</h5>
          <p class="protein" id="total-week-protein">{{weekly_protein}}</p>
        </div>
      </div>
    </div>
  </div>
  <section class="attendance">
    <div class="attendance-list">
      <h1>Food Tracker</h1>
      <table class="table">
        <thead>
          <tr>
            <th>Date</th>
            <th>Food</th>
            <th>Calorie</th>
            <th>Carbs</th>
            <th>Fat</th>
            <th>Protein</th>
            <th>Action</th>
          </tr>
        </thead>
        <tbody>
          {% for food in today_foods %}
          <tr>
            <td>{{food.check_time}}</td>
            <td>{{food.nutrition_name}}</td>
            <td class="calorie">{{food.calorie}}</td>
            <td class="carbs">{{food.carbs}}</td>
            <td class="fat">{{food.fat}}</td>
            <td class="protein">{{food.protein}}</td>
            <td>
              <form
                action="{% url 'my_app:delete_nutrition' food.id %}"
                method="post"
                style="display: inline"
              >
                {% csrf_token %}<button type="submit">Remove</button>
              </form>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </section>
</section>
{% endblock content %}